// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"


var Icons = struct {
	Download *fyne.StaticResource
	Delete *fyne.StaticResource
}{
	Download:&fyne.StaticResource{
		StaticName: "Download.svg",
		StaticContent: []byte("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"256\" height=\"256\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"#E9E9E9\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path stroke=\"none\" d=\"M0 0h24v24H0z\" fill=\"none\"/>\n  <path d=\"M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2\" />\n  <polyline points=\"7 11 12 16 17 11\" />\n  <line x1=\"12\" y1=\"4\" x2=\"12\" y2=\"16\" />\n</svg>"),
	},
	Delete: &fyne.StaticResource{
		StaticName: "Delete.svg",
		StaticContent: []byte("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"256\" height=\"256\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"#E9E9E9\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path stroke=\"none\" d=\"M0 0h24v24H0z\" fill=\"none\"/>\n  <line x1=\"4\" y1=\"7\" x2=\"20\" y2=\"7\" />\n  <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\" />\n  <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\" />\n  <path d=\"M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12\" />\n  <path d=\"M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3\" />\n</svg>"),
	},
}